controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Application;
use app\models\Brands;
use app\models\Carousel;
use app\models\Country;
use app\models\forms\Login;
use app\models\Info;
use app\models\Orders;
use app\models\Pages;
use app\models\Partners;
use app\models\PaymentMethod;
use app\models\PriceFilter;
use app\models\Products;
use app\models\Rayon;
use app\models\Services;
use app\models\Size;
use app\models\Slider;
use app\models\Sms;
use app\models\Socials;
use app\models\User;
use app\models\UserInfo;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\forms\ContactForm;

class SiteController extends Controller
{
    public function init()
    {

        if (!empty(Yii::$app->request->cookies['language'])) {
            Yii::$app->language = Yii::$app->request->cookies['language'];
        } else {
            Yii::$app->language = 'ru';
        }
        parent::init();
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $info = Info::findOne(['id' => 1]);
        $carousel = Carousel::find()->orderBy(['order' => SORT_ASC])->all();
        $slider = Slider::find()
            ->limit(4)
            ->all();
        $slider2 = Slider::find()
            ->offset(4)
            ->limit(4)
            ->all();
        $forman = Products::find()
            ->where(['category_id' => 1])
            ->limit(8)
            ->orderBy(['id' => SORT_DESC])
            ->all();
        $forwoman = Products::find()
            ->where(['category_id' => 2])
            ->limit(8)
            ->orderBy(['id' => SORT_DESC])
            ->all();
        $forchild = Products::find()
            ->where(['category_id' => 3])
            ->limit(8)
            ->orderBy(['id' => SORT_DESC])
            ->all();
        $partners = Partners::find()->where(['status' => 1])->all();
        $payment = PaymentMethod::find()->where(['status' => 1])->all();
        $socials = Socials::find()->where(['status' => 1])->all();
        $model = new Application();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('app', true);
            $model = new Application();
            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->render('index', compact([
            'info',
            'carousel',
            'slider',
            'slider2',
            'forman',
            'forwoman',
            'forchild',
            'partners',
            'payment',
            'services',
            'socials',
        ]));
    }

    public function actionSetlanguage($lang)
    {
        $l = $lang;
        $langs = ['uz', 'ru'];
        if (in_array($l, $langs)) {
            \Yii::$app->language = $l;
            Yii::$app->session->set('app_lang', $l);
            $cookies = Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'language',
                'value' => $l,
            ]));
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Login
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new Login();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->getUser()->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $about = Pages::find()->where(['id' => 1])->one();
        $slider = Slider::find()
            ->limit(4)
            ->all();
        $slider2 = Slider::find()
            ->offset(4)
            ->limit(4)
            ->all();
        $partners = Partners::find()->where(['status' => 1])->all();
        $payment = PaymentMethod::find()->where(['status' => 1])->all();

        return $this->render('about', compact([
            'about',
            'slider',
            'slider2',
            'partners',
            'payment',
        ]));
    }

    public function actionPages($id)
    {
        $about = Pages::find()->where(['id' => $id])->one();
        $slider = Slider::find()
            ->limit(4)
            ->all();
        $slider2 = Slider::find()
            ->offset(4)
            ->limit(4)
            ->all();
        $partners = Partners::find()->where(['status' => 1])->all();
        $payment = PaymentMethod::find()->where(['status' => 1])->all();

        return $this->render('about', compact([
            'about',
            'slider',
            'slider2',
            'partners',
            'payment',
        ]));
    }
//    ================================================================================

    public function actionRestorePassword()
    {

        return $this->render('restore-password');
    }

    public function actionSignUp()
    {
        $username = Yii::$app->request->post('username');
        $password = Yii::$app->request->post('password');
        $email = Yii::$app->request->post('email');
        $phone = Yii::$app->request->post('phone');
        if (Yii::$app->request->post()) {
            $user = new User();
            $user->username = $username;
            $user->setPassword($password);
            $user->email = $email;
            $user->status = 0;
            if ($user->save()) {
                $user_info = new UserInfo();
                $user_info->user_id = $user->id;
                $user_info->phone = $phone;
                $user_info->save(false);
                $sms = new Sms();
                $sms->phone = $phone;
                $sms->sms = 1;
                $sms->save(false);
                return $this->render('activate', ['user_info' => $user_info]);
            }
        } else {
            return $this->render('sign-up');
        }
    }

    public function actionSendCode()
    {
        $phone = Yii::$app->request->post('phone');
        $code = Yii::$app->request->post('code');

        $user = UserInfo::find()->where(['phone' => $phone])->one();
        if (empty($code)) {
            if (!empty($user)) {
                return 1;
            } else {
                return 2;
            }
        } else {
            if (!empty($user)) {
                $id = $user->user_id;
                $sms = Sms::find()->where(['phone' => $phone, 'sms' => $code])->one();
                if (!empty($sms)) {
                    return $this->renderAjax('set-password', compact([
                        'id',
                    ]));
                } else {
                    return 3;
                }
            } else {
                return 2;
            }
        }

        return false;
    }

    public function actionActivate()
    {
        $phone = Yii::$app->request->post('phone');
        $code = Yii::$app->request->post('code');

        $user = UserInfo::find()->where(['phone' => $phone])->one();
        if (empty($code)) {
            if (!empty($user)) {
                return 1;
            } else {
                return 2;
            }
        } else {
            if (!empty($user)) {
                $id = $user->user_id;
                $sms = Sms::find()->where(['phone' => $phone, 'sms' => $code])->one();
                if (!empty($sms)) {
                    $user = User::findOne($id);
                    $user->status = 10;
                    $user->save(false);
                    return $this->renderAjax('welcome');

                } else {
                    return 3;
                }
            } else {
                return 2;
            }
        }

        return false;
    }

    public function actionSendAgain()
    {
        return 1;
    }

    public function actionSetPassword()
    {
        $id = Yii::$app->request->get('id');
        $password = Yii::$app->request->get('password');
        $user = User::findOne($id);
        $user->setPassword($password);
        if ($user->save()) {

views/site/activate.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Activate user';
$this->params['breadcrumbs'][] = $this->title;
?>

<div id="password-reset">
<!-- registration ekrossovki -->


            <div class="registration_top_h1 " >
                <h1><?=Yii::t('app','Регистрация аккаунта на сайте <span>EKROSSOVKI.UZ</span>')?></h1>
            </div>
            <div class="registration_making">
                <h4><?=Yii::t('app','Активировать аккаунт')?></h4>
                <h6>* <?=Yii::t('app','указывает обязательное поле')?></h6>
                <div class="registration_making_all">
                    <?php ActiveForm::begin(['id' => 'get-code', 'action' => Url::to(['site/activate']), 'method' => 'post']); ?>
                        <input type="hidden" name="id" value="<?= $user_info->user_id ?>">
                        <input type="hidden" name="phone" value="<?= $user_info->phone ?>">
                    <div class="registration_making-nball">

                        <div class="registration_making_all_2">
                            <h5>*<?=Yii::t('app','ТЕЛЕФОН НОМЕР')?>.: </h5>
                            <?= Html::input('text', 'phone2',$user_info->phone,['id' => 'phone', 'disabled' => true]) ?>
                        </div>
                        <div class="registration_making_all_3">
                            <button class="1get-code" data-url="<?= Url::to(['site/send-code']) ?>" ><?= Yii::t('app', 'ПОЛУЧИТЬ КОД') ?></button>
                            <h5>*<?=Yii::t('app','ВВЕДИТЕ КОД')?>: </h5>
                            <?= Html::input('text', 'code', '',['id' => 'code','required' => true]) ?>
                        </div>
                        <div class="registration_making_all_1_p">
                            <p><a href="javascript:void(0)" class="send-code-again" data-url="<?= Url::to(['site/send-again']) ?>" ><?= Yii::t('app', 'Попробуйте снова') ?></a></p>
                        </div>

                        <div class="registration_making_all-btn">
                            <button class="check-code" disabled><?=Yii::t('app','АКТИВИРОВАТЬ')?></button>
                        </div>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>

</div>

views/site/change-password.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 10.06.2018
 * Time: 14:58
 */

use yii\helpers\Url;

?>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<section class="set_password_ek login_ek">
    <div class="container">
        <div class="set_password_ek_all login_ek_2div">
            <div class="login_ek_2div-1div">
                <h4><?= Yii::t('app','УСТАНОВИТЬ ПАРОЛЬ') ?></h4>
                <form action="<?= Url::to(['/site/change-password']) ?>" method="get" id="set-pass">
                    <input type="hidden" name="id" value="<?= $id ?>">
                    <div class="set_password_ek_diva">
                        <p>*<?= Yii::t('app','Пароль') ?> </p>
                        <input type="password" name="password" class="set-password" id="password" minlength="6">
                        <p>*<?= Yii::t('app','Подтвердите пароль') ?> </p>
                        <input type="password" name="password-com" class="set-password-com" id="confirm_password" minlength="6">
                        <button class="set-password-btn"><?= Yii::t('app','УСТАНОВИТЬ ПАРОЛЬ') ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
    <section class="welcome thank_you">
        <div class="container">
            <div class="welcome_2divs">

                <div class="welcome_2divs_2">
                    <h2 style="font-size: 80px">404</h2>
                    <h2><?= Yii::t('app','Страница не найдена!') ?></h2>



                </div>
            </div>
        </div>
    </section>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>


<!-- login section -->
<section class="login_ek">
    <div class="container">
        <div class="login_ek_2div">

            <div class="login_ek_2div-1div">
                <h4><?= Yii::t('app', 'ВХОД') ?></h4>
                <?php $form = ActiveForm::begin([
                    'id' => 'login-form',
                    'action' => Url::to(['site/login'])
                ]); ?>

                <?= $form->field($model, 'username', ['template' => '{input}{error}', 'options' => ['tag' => false]])->textInput(['placeholder' => 'Логин'])->label(false) ?>

                <?= $form->field($model, 'password', ['template' => '{input}{error}', 'options' => ['tag' => false]])->passwordInput(['placeholder' => 'Пароль'])->label(false) ?>

                <?= Html::submitButton('ВХОД', ['style' => 'margin-top:0px']) ?>

                <?php ActiveForm::end(); ?>

                <a href="<?= Url::to(['site/restore-password']) ?>"><?= Yii::t('app', 'Забыли пароль') ?>?</a>
            </div>

            <div class="login_ek_2div-2div">
                <h4><?= Yii::t('app', 'ЗАРЕГИСТРИРОВАТЬСЯ') ?></h4>
                <p><?= Yii::t('app', 'Зарегистрируйся на <span>EKROSSOVKI.UZ</span> чтобы получить доступ к своим заказам, отслеживать
                    посылки или создавать список покупок.') ?></p>
                <a href="<?= Url::to(['site/sign-up']) ?>"><?= Yii::t('app', 'СОЗДАТЬ УЧЕТНУЮ ЗАПИСЬ') ?></a>
            </div>

        </div>
    </div>
</section>

views/site/restore-password.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Restore password';
$this->params['breadcrumbs'][] = $this->title;
?>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<style>
    .check-code[disabled]{
        cursor: not-allowed;
    }
</style>
<div id="password-reset">
<!-- restore password -->
<section class="restore_password registration_ek">
    <div class="container">
        <div class="registration_ek-all">
            <div class="registration_making">
                <h4><?= Yii::t('app', 'востановить пароль') ?></h4>
                <h6>* <?= Yii::t('app', 'указывает обязательное поле') ?></h6>
                <div class="registration_making_all">
                    <?php ActiveForm::begin(['id' => 'get-code', 'action' => Url::to(['site/send-code']), 'method' => 'post']); ?>
                    <div class="registration_making-nball">
                        <div class="restore_password_div1 registration_making_all_1">
                            <h5>* <?= Yii::t('app', 'НОМЕР ТЕЛЕФОНА') ?>:</h5>
                            <?= Html::input('text', 'phone', '', ['id' => 'phone', 'required' => true]) ?>
                        </div>

                        <div class="registration_making_all_1_p">
                            <p><?= Yii::t('app', 'Введите номер указаный при регистрации') ?></p>
                        </div>

                        <div class="restore_password_div2 registration_making_all_3">
                            <button class="1get-code"><?= Yii::t('app', 'ПОЛУЧИТЬ КОД') ?></button>
                            <h5>*<?= Yii::t('app', 'ВВЕДИТЕ КОД') ?>: </h5>
                            <?= Html::input('text', 'code', '', ['id' => 'code']) ?>
                        </div>

                        <div class="registration_making_all_1_p restore_passd">
                            <p><a href="javascript:void(0)" class="send-code-again" data-url="<?= Url::to(['site/send-again']) ?>" ><?= Yii::t('app', 'Попробуйте снова') ?></a></p>
                        </div>

                        <div class="registration_making_all-btn restore_passbtn">
                            <button class="check-code" ><?= Yii::t('app', 'ОТПРАВИТЬ') ?></button>
                        </div>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</section>
</div>

views/site/set-password.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 10.06.2018
 * Time: 11:03
 */

use yii\helpers\Url;

?>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<section class="set_password_ek login_ek">
    <div class="container">
        <div class="set_password_ek_all login_ek_2div">
            <div class="login_ek_2div-1div">
                <h4><?= Yii::t('app','УСТАНОВИТЬ ПАРОЛЬ') ?></h4>
                <form action="<?= Url::to(['/site/set-password']) ?>" method="get" id="set-pass">
                    <input type="hidden" name="id" value="<?= $id ?>">
                    <div class="set_password_ek_diva">
                        <p>*<?= Yii::t('app','Пароль') ?> </p>
                        <input type="password" name="password" class="set-password">
                        <p>*<?= Yii::t('app','Подтвердите пароль') ?> </p>
                        <input type="password" name="password-com" class="set-password-com">
                        <button class="set-password-btn"><?= Yii::t('app','УСТАНОВИТЬ ПАРОЛЬ') ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

views/site/sign-up.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Sign up';
$this->params['breadcrumbs'][] = $this->title;
?>


<!-- registration ekrossovki -->
<section class="registration_ek">
    <div class="container">
        <div class="registration_ek-all">
            <div class="registration_top_h1">
                <h1><?=Yii::t('app','Регистрация аккаунта на сайте')?><span>EKROSSOVKI.UZ</span></h1>
            </div>
            <div class="registration_making">
                <h4><?=Yii::t('app','Создать свой аккаунт')?></h4>
                <h6>* <?=Yii::t('app','указывает обязательное поле')?></h6>
                <div class="registration_making_all">
                    <?php ActiveForm::begin(['id' => 'sing-up', 'action' => Url::to(['site/sign-up']), 'method' => 'post']); ?>
                        <div class="registration_making-nball">
                            <div class="registration_making_all_1">
                                <h5>* <?=Yii::t('app','ЛОГИН')?>:</h5>
                                <?= Html::input('text', 'username', '',['required' => true]) ?>
                            </div>
                            <div class="registration_making_all_1_p">
                                <p><?=Yii::t('app','Это имя появляется, когда мы приветствуем вас на нашем сайте')?>.</p>
                            </div>
                            <div class="registration_making_all_2">
                                <h5>*<?=Yii::t('app','ТЕЛЕФОН НОМЕР')?>.: </h5>
                                <?= Html::input('tel', 'phone','',['id' => 'phone', 'required' => true,'pattern' => '[+]{1}[9]{2}[8]{1}[0,1,3,4,5,7,8,9]{1}[1-9]{1}[0-9]{7}','placeholder' => '+998901234567','maxlength'=> '13','minlength' => '9']) ?>
                            </div>
                            <div class="registration_making_all_4">
                                <h5><?=Yii::t('app','EMAIL')?>:</h5>
                                <?= Html::input('email', 'email', '',['required' => false]) ?>
                            </div>
                            <div class="registration_making_all_4">
                                <h5>*<?=Yii::t('app','ПАРОЛЬ')?>:</h5>
                                <?= Html::input('password', 'password', '',['required' => true, 'minlength' => '6','id' => 'password']) ?>
                            </div>
                            <div class="registration_making_all_1_p">
                                <p><?=Yii::t('app','Пароль должен содержать как минимум 6 символов')?></p>
                            </div>
                            <div class="registration_making_all_5">
                                <h5>*<?=Yii::t('app','ПОДТВЕРДИТЕ ПАРОЛЬ')?>: </h5>
                                <?= Html::input('password', 'confirmPassword', '',['required' => true,'minlength' => '6','id' => 'confirm_password']) ?>
                            </div>
                            <div class="registration_making_all-btn">
                                <button type="submit"><?=Yii::t('app','ЗАРЕГИСТРИРОВАТЬСЯ')?></button>
                            </div>
                        </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</section>

views/site/welcome.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 10.06.2018
 * Time: 13:06
 */

use yii\helpers\Url;

?>

    <section class="welcome">
        <div class="container">
            <div class="welcome_2divs">
                <div class="welcome_2divs_1">
                    <h1><?= Yii::t('app','Добро Пожаловать!')?></h1>
                </div>
                <div class="welcome_2divs_2">
                    <h2><?= Yii::t('app','Вы создали аккаунт на сайте') ?> <span>EKROSSOVKI.UZ</span></h2>
                    <p><?= Yii::t('app','Добро пожаловать!') ?></p>
                    <a href="<?= Url::to(['/site/login']) ?>"><?= Yii::t('app','Войти') ?></a>
                </div>
            </div>
        </div>
    </section>